workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

stages:
  - sync

sync-prod:
  tags:
    - gcp-prod
  stage: sync
  image: registry.argondeploy.ru/infra/tools:terraform
  script:
  - export GOOGLE_CREDENTIALS=$GCP_ARGONDEPLOY_KEY
  - cd prod
  - terraform init
  - terraform apply -auto-approve

sync-demo:
  tags:
    - gcp-demo
  stage: sync
  image: registry.argondeploy.ru/infra/tools:terraform
  script:
  - export GOOGLE_CREDENTIALS=$GCP_ARGONDEPLOY_KEY
  - cd demo
  - terraform init
  - terraform apply -auto-approve