cluster:
  # for devops team 
  admin:
  - artesan538@gmail.com
  - gr.azatyan@gmail.com
  - althazari@gmail.com

namespaces:
- name: doubler-prod
  admins: []
  viewers: []
- name: doubler-stage
  admins: []
  viewers: []