cluster:
  admins: []
  viewers: []

namespaces:
- name: udl-prod
  admins: 
  - nekit538@gmail.com
  viewers:
  - artemenko.n.argonlabs@gmail.com
- name: udl-stage
  admins: 
  - nekit538@gmail.com
  viewers:
  - artemenko.n.argonlabs@gmail.com