{{- range .Values.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-admin-role-binding
  namespace: {{ .name }}
subjects:
{{- range .admins }}
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
{{- end}}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
{{- end }}