{{- if .Values.cluster.edit }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-edit-k8s-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
{{- range .Values.cluster.edit }}
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
{{- end}}

{{- end }}
---